### PR TITLE
Prevent UI and Loop from being blocked when playing audio

### LINKED ISSUE #24: Queue cues
Right now we take cues at rely on the promise but there are moments where it fails to play a cue. This could also be related to #20 but essentially we should put it in a queue anyway.

### PR DESCRIPTION
**Pull request by donnyroufs**
closes #24

### CODE REVIEW

File: tests/UserSettingsRepositorySpy.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import { IUserSettingsRepository } from '../src/main/hexagon/ports/IUserSettingsRepository'
+import { Result } from '../src/main/shared-kernel'
+import { UserSettings } from '../src/main/hexagon/UserSettings'
+
+export class UserSettingsRepositorySpy implements IUserSettingsRepository {
```
Comment (donnyroufs) [inline tests/UserSettingsRepositorySpy.ts]: Not needed?
